name: markdown-lint

on:
  pull_request:
    branches:
      - main
      
jobs:
  markdown_lint:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: articulate/actions-markdownlint@v1.1.0
